### ISSUE TITLE
ArgumentError: x outside of string

### ISSUE THREAD

**Issue by qichunren** [zdavatz/spreadsheet#171]
I use Spreadsheet gem to open a xls file, it throw exception: ArgumentError: x outside of string

This is my debug process below:

```
1.9.3-p194 :012 > a
 => "/home/qichunren/200km/T9571-T9572_2016_03_31/data.xls" 
1.9.3-p194 :013 > File.exist?(a)
 => true 
1.9.3-p194 :014 > book = Spreadsheet.open a
ArgumentError: x outside of string
	from /home/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/spreadsheet-1.1.2/lib/spreadsheet/excel/reader.rb:251:in `unpack'
	from /home/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/spreadsheet-1.1.2/lib/spreadsheet/excel/reader.rb:251:in `read_dimensions'
	from /home/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/spreadsheet-1.1.2/lib/spreadsheet/excel/reader.rb:879:in `read_worksheet'
	from /home/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/spreadsheet-1.1.2/lib/spreadsheet/excel/worksheet.rb:53:in `ensure_rows_read'
	from /home/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/spreadsheet-1.1.2/lib/spreadsheet/excel/worksheet.rb:96:in `recalculate_dimensions'
	from /home/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/spreadsheet-1.1.2/lib/spreadsheet/worksheet.rb:147:in `dimensions'
	from /home/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/spreadsheet-1.1.2/lib/spreadsheet/worksheet.rb:265:in `row_count'
	from /home/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/spreadsheet-1.1.2/lib/spreadsheet/worksheet.rb:238:in `inspect'
	from /home/qichunren/.rvm/rubies/ruby-1.9.3-p194/bin/irb:12:in `<main>'

```

And this is my data.xls file in zip.

[data.xls.zip](https://github.com/zdavatz/spreadsheet/files/197344/data.xls.zip)

**Comment by zdavatz** [comment]
thanks for sharing. How did you solve the problem?

**Comment by qichunren** [comment]
@zdavatz I found My excel file has a blank sheet, when I remove it from file, got work.

**Comment by zdavatz** [comment]
thank you for sharing this!
