### ISSUE TITLE
Opening file saved with Calc 5.1.3.2 results in Ole::Storage::FormatError: OLE2 signature is invalid

### ISSUE THREAD

**Issue by matkoniecz** [zdavatz/spreadsheet#176]
Libre Office:

```
Version: 5.1.3.2
Build ID: 1:5.1.3~rc2-0ubuntu1~trusty1
CPU Threads: 2; OS Version: Linux 3.13; UI Render: default; 
Locale: pl-PL (en_US.UTF-8)
```
Lubuntu 32bit

```
ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-linux-gnu]
```

following https://github.com/zdavatz/spreadsheet/blob/master/GUIDE.md results in:

```
book = Spreadsheet.open "test.ods"
Ole::Storage::FormatError: OLE2 signature is invalid
	from /home/mateusz/.gem/ruby/2.3.0/gems/ruby-ole-1.2.12/lib/ole/storage/base.rb:378:in `validate!'
	from /home/mateusz/.gem/ruby/2.3.0/gems/ruby-ole-1.2.12/lib/ole/storage/base.rb:370:in `initialize'
	from /home/mateusz/.gem/ruby/2.3.0/gems/ruby-ole-1.2.12/lib/ole/storage/base.rb:112:in `new'
	from /home/mateusz/.gem/ruby/2.3.0/gems/ruby-ole-1.2.12/lib/ole/storage/base.rb:112:in `load'
	from /home/mateusz/.gem/ruby/2.3.0/gems/ruby-ole-1.2.12/lib/ole/storage/base.rb:79:in `initialize'
	from /home/mateusz/.gem/ruby/2.3.0/gems/ruby-ole-1.2.12/lib/ole/storage/base.rb:85:in `new'
	from /home/mateusz/.gem/ruby/2.3.0/gems/ruby-ole-1.2.12/lib/ole/storage/base.rb:85:in `open'
	from /home/mateusz/.gem/ruby/2.3.0/gems/spreadsheet-1.1.2/lib/spreadsheet/excel/reader.rb:1282:in `setup'
	from /home/mateusz/.gem/ruby/2.3.0/gems/spreadsheet-1.1.2/lib/spreadsheet/excel/reader.rb:140:in `read'
	from /home/mateusz/.gem/ruby/2.3.0/gems/spreadsheet-1.1.2/lib/spreadsheet/excel/workbook.rb:32:in `open'
	from /home/mateusz/.gem/ruby/2.3.0/gems/spreadsheet-1.1.2/lib/spreadsheet.rb:65:in `open'
	from /home/mateusz/.gem/ruby/2.3.0/gems/spreadsheet-1.1.2/lib/spreadsheet.rb:71:in `open'
	from (irb):8
	from /usr/bin/irb:11:in `<main>'
```

**Comment by zdavatz** [comment]
How was the file created? Did you save the file as .xls with LibreOffice?

**Comment by matkoniecz** [comment]
> How was the file created?

Open Calc, save empty file.

Opening xls files produced by this Calc version works fine.

**Comment by zdavatz** [comment]
In what format did you save the file?

**Comment by matkoniecz** [comment]
> book = Spreadsheet.open "test.ods"

ods

**Comment by zdavatz** [comment]
ods Format ist not supported as it is not a Microsoft Format.

**Comment by matkoniecz** [comment]
Note that it is Microsoft Excel compatible spreadsheet (Excel [can](https://support.office.com/en-us/article/Use-Excel-to-open-or-save-a-worksheet-in-the-OpenDocument-Spreadsheet-ods-format-c7114baa-f08a-49eb-aefd-f5d61ed347cd) open it). And this library claims to be capable of opening "Microsoft Excel compatible spreadsheets".

**Comment by matkoniecz** [comment]
If it is capable of opening only xls/xlsx then "xls/xslx" would be probably better term than "Microsoft Excel compatible spreadsheet".

**Comment by zdavatz** [comment]
xlsx is not supported.
